AWSTemplateFormatVersion: "2010-09-09"
Description: A template for setting up database 

Parameters:
  # Default settings
  ProjectName:
    Type: String

  # DB setup
  EngineType:
    Type: String 
    Default: mariadb

  DBUsername:
    Type: String 

  DBUserPassword:
    Type: String 
  
  DBName:
    Type: String 

  DBInstanceClass:
    Type: String 
    Default: db.t3.micro
  
  AllocatedStorage:
    Type: Number 
    Default: 20

Resources:
  DBSubnet:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub ${ProjectName}-db-subnetgroup 
      DBSubnetGroupDescription: DB subnet group for db instances 
      SubnetIds: 
        - !ImportValue DBSubnet1
        - !ImportValue DBSubnet2

  DB:
    Type: AWS::RDS::DBInstance
    DependsOn: 
      - DBSubnet
    Properties:
      AllocatedStorage: !Ref AllocatedStorage 
      DBInstanceIdentifier: !Sub ${ProjectName}-db
      AutoMinorVersionUpgrade: false
      DBInstanceClass: !Ref DBInstanceClass
      Engine: !Ref EngineType
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBUserPassword
      DBSubnetGroupName: !Ref DBSubnet
      VPCSecurityGroups:
        - !ImportValue DBSG
      DBName: !Ref DBName

Outputs: 
  DBEndpoint:
    Value: !GetAtt DB.Endpoint.Address
    Export:
      Name: DBEndpoint

  DBUsername:
    Value: !Ref DBUsername
    Export:
      Name: DBUsername

  DBUserPassword:
    Value: !Ref DBUserPassword
    Export:
      Name: DBUserPassword

  DBName:
    Value: !Ref DBName
    Export:
      Name: DBName