AWSTemplateFormatVersion: "2010-09-09"
Description: A template for setting up database 

Parameters:
  # Default settings
  ProjectName:
    Type: String

  # DB setup
  EngineType:
    Type: String 
    Default: mariadb

  MasterUsername:
    Type: String 
    Default: admin

  MasterUserPassword:
    Type: String 
    Default: admin-password
  
  DBInstanceClass:
    Type: String 
    Default: db.t3.micro
  
  AllocatedStorage:
    Type: Number 
    Default: 20

  DBName:
    Type: String 
    Default: MyPlaylist

Resources:
  DBSubnet:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub ${ProjectName}-db-subnetgroup 
      DBSubnetGroupDescription: DB subnet group for db instances 
      SubnetIds: 
        - !ImportValue DBSubnet1
        - !ImportValue DBSubnet2

  DB:
    Type: AWS::RDS::DBInstance
    DependsOn: 
      - DBSubnet
    Properties:
      AllocatedStorage: !Ref AllocatedStorage 
      DBInstanceIdentifier: !Sub ${ProjectName}-db
      AutoMinorVersionUpgrade: false
      DBInstanceClass: !Ref DBInstanceClass
      Engine: !Ref EngineType
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBSubnetGroupName: !Ref DBSubnet
      VPCSecurityGroups:
        - !ImportValue DBSG
      DBName: !Ref DBName

Outputs: 
  Endpoint:
    Value: !GetAtt DB.Endpoint.Address
    Export:
      Name: DBEndpoint

  Username:
    Value: !Ref MasterUsername
    Export:
      Name: DBUsername

  PWD:
    Value: !Ref MasterUserPassword
    Export:
      Name: DBPWD


  DBName:
    Value: !Ref DBName
    Export:
      Name: DBName