AWSTemplateFormatVersion: "2010-09-09"
Description: A template for setting up web servers

Parameters:
  # Default settings
  ProjectName:
    Type: String
  
  InstanceType:
    Type: String 
    Default: t2.micro
  
  ImageId:
    Type: String 
  
  KeyName:
    Type: String 
    Default: web

  EFSFileSystemId: 
    Type: String 

  NlbDns: 
    Type: String 

  EfsDns: 
    Type: String 

Resources:
##########################
# Set up the IAM role
##########################
  WebServerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-web-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonRDSDataFullAccess #TODO
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess

##########################
# Set up the auto scaling group 
##########################
  IamInstanceProfile:
    DependsOn:
      - WebServerRole
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${ProjectName}-web-profile
      Roles:
        - !Sub ${ProjectName}-web-role

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      LaunchConfigurationName: !Sub ${ProjectName}-web-template
      KeyName: !Ref KeyName
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId  
      SecurityGroups: 
        - !ImportValue WEBSG
      IamInstanceProfile: !GetAtt IamInstanceProfile.Arn
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          
          # Install libs
          sudo yum install -y nginx

          # Enable web server
          sudo systemctl enable --now nginx

          echo -e "location ~ [^/].php(/|$) {\n    fastcgi_split_path_info ^(.+?\.php)(/.*)$;\n    set \$path_info \$fastcgi_path_info;\n    fastcgi_index index.php;\n    include fastcgi_params;\n    fastcgi_pass ${NlbDns}:9000;\n    fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;\n}\n\n# Deny access to .htaccess files\nlocation ~ /.ht {\n    deny all;\n}\n\nlocation / {\n    index index.php index.html;\n    try_files \$uri \$uri/ /index.php\$uri?\$query_string;\n}" | sudo tee /etc/nginx/default.d/php.conf > /dev/null

          # Mount EFS
          sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport ${EfsDns}:/ /usr/share/nginx/html

          sudo systemctl restart nginx


  AutoScalingGroup:
    DependsOn:
      - LaunchConfiguration
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${ProjectName}-web-autoscaling
      MinSize: 1
      MaxSize: 1
      DesiredCapacity: 1 
      LaunchConfigurationName: !Sub ${ProjectName}-web-template
      TargetGroupARNs:
        - !ImportValue ALBTargetGroupArn
      VPCZoneIdentifier:
        - !ImportValue WebSubnet1
        - !ImportValue WebSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-web
          PropagateAtLaunch: true












